Repository ssg-240304-java2/final-sulbao, pull requests merged in 2024-08, with the labels that each got.

#100 Featuer: 상품 정보관리 기능 개발
  .gitignore
  src/main/java/com/finalproject/sulbao/common/file/FileService.java
  src/main/java/com/finalproject/sulbao/product/controller/ProductController.java
  src/main/java/com/finalproject/sulbao/product/model/dto/ProductDTO.java
  src/main/java/com/finalproject/sulbao/product/model/entity/Magazine.java
  src/main/java/com/finalproject/sulbao/product/model/entity/Product.java
  src/main/java/com/finalproject/sulbao/product/model/entity/ProductCategory.java
  src/main/java/com/finalproject/sulbao/product/model/entity/Review.java
  src/main/java/com/finalproject/sulbao/product/model/service/ProductService.java
  src/main/java/com/finalproject/sulbao/product/model/vo/MagazineImage.java
  src/main/java/com/finalproject/sulbao/product/model/vo/ProductImage.java
  src/main/java/com/finalproject/sulbao/product/repository/ProductRepository.java
  src/main/java/com/finalproject/sulbao/product/service/ProductService.java
  src/main/resources/templates/product/productDetail.html
  src/main/resources/templates/product/productList.html
  src/main/resources/templates/product/productUpdate.html
Labels: :memo: Status: Review Needed

#101 feature: 장바구니 및 결제 기능 개발
  src/main/java/com/finalproject/sulbao.zip
  src/main/java/com/finalproject/sulbao/cart/controller/CartController.java
  src/main/java/com/finalproject/sulbao/cart/controller/KakaoController.java
  src/main/java/com/finalproject/sulbao/cart/domain/Carts.java
  src/main/java/com/finalproject/sulbao/cart/dto/ApproveResponse.java
  src/main/java/com/finalproject/sulbao/cart/dto/CartDTO.java
  src/main/java/com/finalproject/sulbao/cart/dto/ReadyResponse.java
  src/main/java/com/finalproject/sulbao/cart/repository/CartRepository.java
  src/main/java/com/finalproject/sulbao/cart/service/CartService.java
  src/main/java/com/finalproject/sulbao/cart/service/KakaoPayService.java
  src/main/java/com/finalproject/sulbao/cart/session/SessionUtils.java
  src/main/resources/templates/cart.html
  src/main/resources/templates/order.html
  src/main/resources/templates/presentOrder.html
Labels: ✨ Type: Feature, :memo: Status: Review Needed

#102 술포스트 및 댓글 구현
  src/main/java/com/finalproject/sulbao/board/controller/CommentController.java
  src/main/java/com/finalproject/sulbao/board/controller/LikeController.java
  src/main/java/com/finalproject/sulbao/board/controller/ZzanfeedController.java
  src/main/java/com/finalproject/sulbao/board/controller/ZzanpostController.java
  src/main/java/com/finalproject/sulbao/board/domain/Comment.java
  src/main/java/com/finalproject/sulbao/board/domain/Like.java
  src/main/java/com/finalproject/sulbao/board/domain/Post.java
  src/main/java/com/finalproject/sulbao/board/dto/PostDto.java
  src/main/java/com/finalproject/sulbao/board/dto/UserDto.java
  src/main/java/com/finalproject/sulbao/board/repository/LikeRepository.java
  src/main/java/com/finalproject/sulbao/board/service/CommentService.java
  src/main/java/com/finalproject/sulbao/board/service/LikeService.java
  src/main/java/com/finalproject/sulbao/board/service/PostService.java
  src/main/java/com/finalproject/sulbao/cart/repository/ProductRepository.java
  src/main/java/com/finalproject/sulbao/cart/service/ProductService.java
  src/main/java/com/finalproject/sulbao/login/model/entity/StatusType.java
  src/main/java/com/finalproject/sulbao/product/model/entity/Magazine.java
  src/main/java/com/finalproject/sulbao/product/model/entity/Product.java
  src/main/java/com/finalproject/sulbao/product/model/service/ProductService.java
  src/main/resources/static/board/zzanfeed/new.css
  src/main/resources/static/board/zzanpost/detail.css
  src/main/resources/templates/board/zzanfeed/new.html
  src/main/resources/templates/board/zzanpost/detail.html
  src/main/resources/templates/board/zzanpost/edit.html
  src/main/resources/templates/board/zzanpost/list.html
  src/main/resources/templates/board/zzanpost/new.html
  src/test/java/com/finalproject/sulbao/EntityTest.java
Labels: :memo: Status: Review Needed

#105 장바구니 회원 세션 연결
  src/main/java/com/finalproject/sulbao/cart/controller/CartController.java
  src/main/resources/templates/common/fragment/user/footer.html
  src/main/resources/templates/common/fragment/user/header.html
Labels: :memo: Status: Review Needed

#107 Fix: 상품 로그인 정보 연결
  src/main/java/com/finalproject/sulbao/TempController.java
  src/main/java/com/finalproject/sulbao/login/model/entity/MemberInfo.java
  src/main/java/com/finalproject/sulbao/product/controller/ProductController.java
  src/main/java/com/finalproject/sulbao/product/model/dto/ProductDTO.java
  src/main/java/com/finalproject/sulbao/product/service/ProductService.java
  src/main/resources/static/admin/js/custom.js
  src/main/resources/templates/product/productDetail.html
  src/main/resources/templates/product/productList.html
Labels: :memo: Status: Review Needed

#109 docs: 배포를 위한 application.yml파일 수정
  src/main/resources/application-secret-prod.yml
  src/main/resources/application.yml
Labels: :memo: Status: Review Needed, 📃 Type: Docs

#110 docs: Update sulbao-cicd.yml
  .github/workflows/sulbao-cicd.yml
Labels: :memo: Status: Review Needed, 📃 Type: Docs

#114 feat: 상품리뷰 기능 개발
  src/main/java/com/finalproject/sulbao/product/model/entity/Review.java
  src/main/java/com/finalproject/sulbao/review/controller/ReviewController.java
  src/main/java/com/finalproject/sulbao/review/model/dto/ReviewDTO.java
  src/main/java/com/finalproject/sulbao/review/repository/OrderRepository.java
  src/main/java/com/finalproject/sulbao/review/repository/ReviewRepository.java
  src/main/java/com/finalproject/sulbao/review/service/ReviewService.java
  src/main/resources/templates/common/layouts/userDefault.html
  src/main/resources/templates/review/detail.html
  src/main/resources/templates/review/list.html
  src/main/resources/templates/review/orderList.html
  src/main/resources/templates/review/regist.html
  src/main/resources/templates/review/update.html
Labels: :memo: Status: Review Needed

#115 docs: cicd 배포 파일 수정
  .github/workflows/sulbao-cicd.yml
Labels: :memo: Status: Review Needed

#116 FIx : 로그인 컨트롤러 경로 수정
  src/main/java/com/finalproject/sulbao/login/controller/EmailController.java
  src/main/java/com/finalproject/sulbao/login/controller/LoginController.java
  src/main/java/com/finalproject/sulbao/login/controller/LoginViewController.java
  src/main/java/com/finalproject/sulbao/login/controller/UserAuthenticationSuccessHandler.java
  src/main/java/com/finalproject/sulbao/login/model/dto/EmailConfirmDto.java
  src/main/java/com/finalproject/sulbao/login/model/dto/LoginDetails.java
  src/main/java/com/finalproject/sulbao/login/model/dto/SignupSellerDto.java
  src/main/java/com/finalproject/sulbao/login/model/entity/EmailVerify.java
  src/main/java/com/finalproject/sulbao/login/model/entity/Login.java
  src/main/java/com/finalproject/sulbao/login/model/entity/RoleType.java
  src/main/java/com/finalproject/sulbao/login/model/entity/StatusType.java
  src/main/java/com/finalproject/sulbao/login/model/repository/EmailRepository.java
  src/main/java/com/finalproject/sulbao/login/model/repository/LoginRepository.java
  src/main/java/com/finalproject/sulbao/login/model/service/EmailService.java
  src/main/java/com/finalproject/sulbao/login/model/service/LoginService.java
  src/main/resources/static/user/css/login-style.css
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/auth/signup-seller.html
  src/main/resources/templates/auth/signup.html
  src/main/resources/templates/auth/testSeller.html
  src/main/resources/templates/auth/testadmin.html
  src/main/resources/templates/auth/verify-email.html
  src/main/resources/templates/auth/verifyagePage.html
  src/test/java/com/finalproject/sulbao/EntityTest.java
Labels: 🔨 Type: Fix

#117 feat: 일반 결제 및 선결제 메일전송 전
  src/main/java/com/finalproject/sulbao/SulbaoApplication.java
  src/main/java/com/finalproject/sulbao/TempController.java
  src/main/java/com/finalproject/sulbao/cart/controller/CartController.java
  src/main/java/com/finalproject/sulbao/cart/controller/KakaoController.java
  src/main/java/com/finalproject/sulbao/cart/domain/Carts.java
  src/main/java/com/finalproject/sulbao/cart/domain/Order.java
  src/main/java/com/finalproject/sulbao/cart/dto/OrderDTO.java
  src/main/java/com/finalproject/sulbao/cart/dto/OrderItemDTO.java
  src/main/java/com/finalproject/sulbao/cart/repository/CartRepository.java
  src/main/java/com/finalproject/sulbao/cart/repository/OrderRepository.java
  src/main/java/com/finalproject/sulbao/cart/service/CartService.java
  src/main/java/com/finalproject/sulbao/cart/service/KakaoPayService.java
  src/main/java/com/finalproject/sulbao/cart/service/OrderItemService.java
  src/main/java/com/finalproject/sulbao/cart/service/OrderService.java
  src/main/java/com/finalproject/sulbao/config/WebSecurityConfig.java
  src/main/java/com/finalproject/sulbao/login/model/entity/MemberInfo.java
  src/main/resources/templates/order.html
  src/main/resources/templates/ordercomplete.html
  src/main/resources/templates/presentOrder.html
Labels: ✨ Type: Feature, :memo: Status: Review Needed

#120 !HOTFIX: 배포시 발생한 오류 수정
  src/main/java/com/finalproject/sulbao/review/repository/OrderRepository.java
  src/main/java/com/finalproject/sulbao/review/service/ReviewService.java
  src/main/resources/templates/common/layouts/userDefault.html
Labels: :memo: Status: Review Needed

#122 !HOTFIX: redirect 오류 수정
  src/main/java/com/finalproject/sulbao/login/controller/UserAuthenticationSuccessHandler.java
Labels: :memo: Status: Review Needed

#125 fix: 상품 리뷰 조회, 등록 기능 수정
  src/main/java/com/finalproject/sulbao/product/controller/ProductController.java
  src/main/java/com/finalproject/sulbao/review/controller/ReviewController.java
  src/main/java/com/finalproject/sulbao/review/service/ReviewService.java
  src/main/resources/templates/review/detail.html
  src/main/resources/templates/review/regist.html
Labels: :memo: Status: Review Needed

#134 검색 기능
  src/main/java/com/finalproject/sulbao/board/common/BoardCategoryConstants.java
  src/main/java/com/finalproject/sulbao/board/controller/SearchController.java
  src/main/java/com/finalproject/sulbao/board/repository/PostRepository.java
  src/main/java/com/finalproject/sulbao/board/service/PostService.java
  src/main/resources/application.yml
  src/main/resources/static/board/search.css
  src/main/resources/templates/board/search-results.html
  src/main/resources/templates/board/zzanfeed/detail.html
  src/main/resources/templates/board/zzanfeed/edit.html
  src/main/resources/templates/board/zzanfeed/list.html
  src/main/resources/templates/board/zzanfeed/new.html
  src/main/resources/templates/board/zzanpost/detail.html
  src/main/resources/templates/board/zzanpost/edit.html
  src/main/resources/templates/board/zzanpost/list.html
  src/main/resources/templates/board/zzanpost/new.html
Labels: :memo: Status: Review Needed

#135 design: 상품리스트, 최저가 조회 화면 구성
  src/main/java/com/finalproject/sulbao/product/controller/ProductController.java
  src/main/java/com/finalproject/sulbao/product/model/dto/ProductComparisonDTO.java
  src/main/java/com/finalproject/sulbao/product/model/dto/ProductDTO.java
  src/main/java/com/finalproject/sulbao/product/model/entity/Product.java
  src/main/java/com/finalproject/sulbao/product/model/entity/ProductComparison.java
  src/main/java/com/finalproject/sulbao/product/model/vo/ComparisonImage.java
  src/main/java/com/finalproject/sulbao/product/repository/ProductComparisonRepository.java
  src/main/java/com/finalproject/sulbao/product/service/ProductService.java
  src/main/resources/templates/adm/product/productDetail.html
  src/main/resources/templates/adm/product/productList.html
  src/main/resources/templates/adm/product/productUpdate.html
  src/main/resources/templates/product/detail.html
  src/main/resources/templates/product/list.html
Labels: :memo: Status: Review Needed

#139 design: 관리자 및 사용자 매거진 화면디자인
  src/main/java/com/finalproject/sulbao/auth/controller/AuthController.java
  src/main/java/com/finalproject/sulbao/login/controller/UserAuthenticationSuccessHandler.java
  src/main/java/com/finalproject/sulbao/magazine/controller/MagazineController.java
  src/main/java/com/finalproject/sulbao/product/controller/ProductController.java
  src/main/resources/static/admin/js/custom.js
  src/main/resources/templates/admin/index.html
  src/main/resources/templates/admin/magazine/detail.html
  src/main/resources/templates/admin/magazine/list.html
  src/main/resources/templates/admin/product/productDetail.html
  src/main/resources/templates/admin/product/productList.html
  src/main/resources/templates/admin/product/productUpdate.html
  src/main/resources/templates/common/fragment/admin/aside.html
  src/main/resources/templates/index.html
  src/main/resources/templates/magazine/list.html
Labels: :memo: Status: Review Needed

#141 feature: 판매자 주문 조회
  src/main/java/com/finalproject/sulbao/cart/controller/OrderController.java
  src/main/java/com/finalproject/sulbao/cart/dto/OrderProductDTO.java
  src/main/java/com/finalproject/sulbao/cart/dto/ProductDTO.java
  src/main/java/com/finalproject/sulbao/cart/repository/OrderRepository.java
  src/main/java/com/finalproject/sulbao/cart/repository/ProductRepository.java
  src/main/java/com/finalproject/sulbao/cart/service/OrderProductService.java
  src/main/java/com/finalproject/sulbao/cart/service/OrderService.java
  src/main/java/com/finalproject/sulbao/cart/service/ProductService.java
  src/main/java/com/finalproject/sulbao/product/repository/ProductRepository.java
  src/main/resources/templates/present-email.html
  src/main/resources/templates/sellerorder.html
Labels: ✨ Type: Feature, :memo: Status: Review Needed

#142 fix: 관리자, 사용자 메뉴 연결
  src/main/java/com/finalproject/sulbao/board/controller/PostController.java
  src/main/java/com/finalproject/sulbao/cart/controller/OrderController.java
  src/main/java/com/finalproject/sulbao/magazine/controller/MagazineController.java
  src/main/java/com/finalproject/sulbao/product/controller/ProductController.java
  src/main/resources/templates/common/fragment/admin/aside.html
  src/main/resources/templates/common/fragment/user/header.html
Labels: :memo: Status: Review Needed

#143 feat: 회원의 나의 게시글 조회 기능
  src/main/java/com/finalproject/sulbao/board/controller/BoardController.java
  src/main/java/com/finalproject/sulbao/board/dto/PostDto.java
  src/main/java/com/finalproject/sulbao/board/repository/PostRepository.java
  src/main/java/com/finalproject/sulbao/board/service/PostService.java
  src/main/resources/static/board/user/list.css
  src/main/resources/templates/board/user/list.html
Labels: :memo: Status: Review Needed

#145 fix: 화면 url 수정 및 MixContent 수정
  src/main/java/com/finalproject/sulbao/board/controller/SearchController.java
  src/main/java/com/finalproject/sulbao/board/controller/ZzanfeedController.java
  src/main/java/com/finalproject/sulbao/board/controller/ZzanpostController.java
  src/main/resources/templates/common/layouts/adminDefault.html
Labels: :memo: Status: Review Needed

#148 feat: 판매자 주문 조회 및 검색 및 상태 변경
  src/main/java/com/finalproject/sulbao/cart/controller/CartController.java
  src/main/java/com/finalproject/sulbao/cart/controller/KakaoController.java
  src/main/java/com/finalproject/sulbao/cart/controller/OrderController.java
  src/main/java/com/finalproject/sulbao/cart/repository/OrderRepository.java
  src/main/java/com/finalproject/sulbao/cart/service/KakaoPayService.java
  src/main/java/com/finalproject/sulbao/cart/service/OrderService.java
  src/main/java/com/finalproject/sulbao/login/model/service/EmailService.java
  src/main/resources/templates/cart/cart.html
  src/main/resources/templates/cart/order.html
  src/main/resources/templates/cart/ordercomplete.html
  src/main/resources/templates/cart/presentOrder.html
  src/main/resources/templates/cart/sellerorder.html
  src/main/resources/templates/cart/success.html
  src/main/resources/templates/present-email.html
Labels: ✨ Type: Feature, :memo: Status: Review Needed

#153 feat: Admin주문 조회 화면 및 기능
  src/main/java/com/finalproject/sulbao/cart/controller/OrderController.java
  src/main/java/com/finalproject/sulbao/cart/service/OrderProductService.java
  src/main/resources/templates/cart/sellerorder.html
Labels: ✨ Type: Feature, :memo: Status: Review Needed

#154 fix : bbaton url 오류 수정
  src/main/java/com/finalproject/sulbao/login/controller/LoginController.java
  src/main/resources/templates/common/fragment/user/header.html
Labels: 🔨 Type: Fix

#155 feat: 상품 상세페이지 및 장바구니 추가 기능
  .gitignore
  src/main/java/com/finalproject/sulbao/product/controller/ProductController.java
  src/main/java/com/finalproject/sulbao/product/controller/UserProductController.java
  src/main/java/com/finalproject/sulbao/product/model/entity/Product.java
  src/main/java/com/finalproject/sulbao/product/service/ProductService.java
  src/main/resources/application.yml
  src/main/resources/templates/about.html
  src/main/resources/templates/common/fragment/admin/aside.html
  src/main/resources/templates/common/fragment/admin/header.html
  src/main/resources/templates/common/fragment/user/aside.html
  src/main/resources/templates/common/fragment/user/footer.html
  src/main/resources/templates/common/fragment/user/header.html
  src/main/resources/templates/common/layouts/mypageDefault.html
  src/main/resources/templates/contact.html
  src/main/resources/templates/elements.html
  src/main/resources/templates/mypage/myprofile.html
  src/main/resources/templates/product/detail.html
  src/main/resources/templates/product/list.html
  src/main/resources/templates/product/low.html
  src/main/resources/templates/review/detail.html
  src/main/resources/templates/review/list.html
  src/main/resources/templates/review/orderList.html
  src/main/resources/templates/review/regist.html
  src/main/resources/templates/review/update.html
  src/main/resources/templates/services.html
Labels: :memo: Status: Review Needed

#168 20240822: 오전 배포
  .gitignore
  src/main/java/com/finalproject/sulbao/cart/controller/OrderController.java
  src/main/java/com/finalproject/sulbao/cart/service/OrderProductService.java
  src/main/java/com/finalproject/sulbao/login/controller/LoginController.java
  src/main/java/com/finalproject/sulbao/product/controller/ProductController.java
  src/main/java/com/finalproject/sulbao/product/controller/UserProductController.java
  src/main/java/com/finalproject/sulbao/product/model/entity/Product.java
  src/main/java/com/finalproject/sulbao/product/service/ProductService.java
  src/main/resources/application.yml
  src/main/resources/templates/about.html
  src/main/resources/templates/cart/sellerorder.html
  src/main/resources/templates/common/fragment/admin/aside.html
  src/main/resources/templates/common/fragment/admin/header.html
  src/main/resources/templates/common/fragment/user/aside.html
  src/main/resources/templates/common/fragment/user/footer.html
  src/main/resources/templates/common/fragment/user/header.html
  src/main/resources/templates/common/layouts/mypageDefault.html
  src/main/resources/templates/contact.html
  src/main/resources/templates/elements.html
  src/main/resources/templates/mypage/myprofile.html
  src/main/resources/templates/product/detail.html
  src/main/resources/templates/product/list.html
  src/main/resources/templates/product/low.html
  src/main/resources/templates/review/detail.html
  src/main/resources/templates/review/list.html
  src/main/resources/templates/review/orderList.html
  src/main/resources/templates/review/regist.html
  src/main/resources/templates/review/update.html
  src/main/resources/templates/services.html
Labels: :memo: Status: Review Needed

#170 feat: 상품 카트에 담기 로직 완료
  src/main/java/com/finalproject/sulbao/cart/repository/CartRepository.java
  src/main/java/com/finalproject/sulbao/cart/service/CartService.java
  src/main/java/com/finalproject/sulbao/product/controller/UserProductController.java
Labels: ✨ Type: Feature, :memo: Status: Review Needed

#171 Design: css 수정
  src/main/java/com/finalproject/sulbao/board/common/SessionHandler.java
  src/main/java/com/finalproject/sulbao/board/controller/BoardController.java
  src/main/java/com/finalproject/sulbao/board/controller/ZzanfeedController.java
  src/main/java/com/finalproject/sulbao/board/controller/ZzanpostController.java
  src/main/java/com/finalproject/sulbao/board/dto/UserDto.java
  src/main/java/com/finalproject/sulbao/login/controller/MemberProfileController.java
  src/main/java/com/finalproject/sulbao/login/model/service/LoginService.java
  src/main/resources/static/board/search.css
  src/main/resources/static/board/zzanfeed/list.css
  src/main/resources/static/board/zzanpost/list.css
  src/main/resources/templates/board/admin/list.html
  src/main/resources/templates/board/search-results.html
  src/main/resources/templates/board/user/list.html
  src/main/resources/templates/board/zzanfeed/detail.html
  src/main/resources/templates/board/zzanfeed/list.html
  src/main/resources/templates/board/zzanpost/detail.html
  src/main/resources/templates/board/zzanpost/list.html
  src/main/resources/templates/index.html
  src/test/java/com/finalproject/sulbao/EntityTest.java
Labels: :memo: Status: Review Needed

#172 fix : 커밋 이력 삭제 및 스타일 수정
  src/main/java/com/finalproject/sulbao/login/controller/LoginController.java
  src/main/resources/static/user/css/login-style.css
  src/main/resources/static/user/css/main-style.css
  src/main/resources/static/user/css/style.css
  src/main/resources/static/user/images/mainpage/main-banner.png
  src/main/resources/static/user/images/mainpage/main-post-01.jpeg
  src/main/resources/static/user/images/mainpage/main-post-02.jpg
  src/main/resources/static/user/images/mainpage/main-post-03.jpg
  src/main/resources/static/user/images/mainpage/main-post-04.jpg
  src/main/resources/static/user/images/mainpage/main-zzan-01.jpg
  src/main/resources/static/user/images/mainpage/main-zzan-02.jpg
  src/main/resources/static/user/images/mainpage/main-zzan-03.png
  src/main/resources/static/user/images/mainpage/main-zzan-04.jpg
  src/main/resources/static/user/images/mainpage/main-zzan-05.jpg
  src/main/resources/static/user/images/mainpage/main-zzan-06.jpg
  src/main/resources/static/user/images/mainpage/profile-01.jpeg
  src/main/resources/static/user/images/mainpage/profile-02.jpg
  src/main/resources/static/user/images/mainpage/profile-03.jpg
  src/main/resources/static/user/images/mainpage/profile-04.jpg
  src/main/resources/static/user/images/mainpage/profile-05.jpg
  src/main/resources/static/user/images/mainpage/profile-06.jpg
  src/main/resources/templates/auth/verifyagePage.html
  src/main/resources/templates/common/fragment/user/header.html
  src/main/resources/templates/index.html
Labels: 🔨 Type: Fix

#173 feat: 사용자 상품 리스트 조회
  src/main/java/com/finalproject/sulbao/product/controller/UserProductController.java
  src/main/java/com/finalproject/sulbao/product/model/dto/ProductComparisonDTO.java
  src/main/java/com/finalproject/sulbao/product/repository/ProductComparisonRepository.java
  src/main/java/com/finalproject/sulbao/product/repository/ProductRepository.java
  src/main/java/com/finalproject/sulbao/product/service/ProductService.java
  src/main/resources/templates/common/layouts/adminDefault.html
  src/main/resources/templates/common/layouts/userDefault.html
  src/main/resources/templates/product/detail.html
  src/main/resources/templates/product/list.html
Labels: :memo: Status: Review Needed

#174 feat: 마이페이지조회
  src/main/java/com/finalproject/sulbao/cart/controller/CartController.java
  src/main/java/com/finalproject/sulbao/cart/controller/KakaoController.java
  src/main/java/com/finalproject/sulbao/cart/controller/OrderController.java
  src/main/java/com/finalproject/sulbao/cart/dto/OrderListDTO.java
  src/main/java/com/finalproject/sulbao/cart/repository/CartRepository.java
  src/main/java/com/finalproject/sulbao/cart/repository/OrderRepository.java
  src/main/java/com/finalproject/sulbao/cart/service/OrderService.java
  src/main/java/com/finalproject/sulbao/login/model/service/EmailService.java
  src/main/resources/templates/cart/memberorder.html
  src/main/resources/templates/common/fragment/user/aside.html
  src/main/resources/templates/error.html
  src/main/resources/templates/present-email.html
Labels: ✨ Type: Feature, :memo: Status: Review Needed

#175 게시판 디자인 수정
  src/main/java/com/finalproject/sulbao/login/model/service/LoginService.java
  src/main/resources/application.yml
  src/main/resources/static/board/user/list.css
  src/main/resources/static/board/zzanfeed/detail.css
  src/main/resources/static/board/zzanfeed/edit.css
  src/main/resources/static/board/zzanfeed/list.css
  src/main/resources/static/board/zzanfeed/new.css
  src/main/resources/static/board/zzanpost/detail.css
  src/main/resources/static/board/zzanpost/list.css
  src/main/resources/templates/board/user/list.html
  src/main/resources/templates/board/zzanfeed/detail.html
  src/main/resources/templates/board/zzanfeed/edit.html
  src/main/resources/templates/board/zzanfeed/list.html
  src/main/resources/templates/board/zzanfeed/new.html
  src/main/resources/templates/board/zzanpost/detail.html
  src/main/resources/templates/index.html
Labels: :memo: Status: Review Needed

#177 feat: 마이페이지 주문내역 조회
  src/main/java/com/finalproject/sulbao/cart/controller/CartController.java
  src/main/java/com/finalproject/sulbao/cart/controller/KakaoController.java
  src/main/java/com/finalproject/sulbao/cart/controller/OrderController.java
  src/main/java/com/finalproject/sulbao/cart/dto/OrderListDTO.java
  src/main/resources/templates/cart/memberorder.html
Labels: ✨ Type: Feature, :memo: Status: Review Needed

#178 fix: 이메일 스타일 변경
  src/main/resources/templates/present-email.html
Labels: 🔨 Type: Fix

#179 design: 마이페이지 디자인 수정
  src/main/java/com/finalproject/sulbao/board/controller/BoardController.java
  src/main/java/com/finalproject/sulbao/cart/controller/OrderController.java
  src/main/java/com/finalproject/sulbao/login/controller/MemberProfileController.java
  src/main/java/com/finalproject/sulbao/review/controller/ReviewController.java
  src/main/resources/templates/common/fragment/user/aside.html
  src/main/resources/templates/mypage/myprofile.html
  src/main/resources/templates/mypage/pro-form.html
Labels: :memo: Status: Review Needed

#181 Fix: 게시판 관련 버그 해결
  .github/workflows/sulbao-cicd.yml
  .gitignore
  gradlew.bat
  src/main/java/com/finalproject/sulbao/board/common/BoardCategoryConstants.java
  src/main/java/com/finalproject/sulbao/board/controller/ManagementController.java
  src/main/java/com/finalproject/sulbao/board/dto/AdminPostSearchRequestDto.java
  src/main/java/com/finalproject/sulbao/board/repository/PostRepository.java
  src/main/java/com/finalproject/sulbao/board/repository/PostSpecification.java
  src/main/java/com/finalproject/sulbao/board/service/PostService.java
  src/main/resources/application.yml
  src/main/resources/static/board/admin/list.css
  src/main/resources/static/board/search.css
  src/main/resources/templates/board/admin/list.html
  src/main/resources/templates/board/search-results.html
  src/main/resources/templates/board/zzanfeed/detail.html
  src/main/resources/templates/common/layouts/userDefault.html
Labels: :memo: Status: Review Needed

#182 feat: 상품 최저가 조회 및 메인 상품
  src/main/java/com/finalproject/sulbao/TempController.java
  src/main/java/com/finalproject/sulbao/auth/controller/AuthController.java
  src/main/java/com/finalproject/sulbao/product/controller/UserProductController.java
  src/main/java/com/finalproject/sulbao/product/repository/ProductComparisonRepository.java
  src/main/java/com/finalproject/sulbao/product/repository/ProductRepository.java
  src/main/java/com/finalproject/sulbao/product/service/ProductService.java
  src/main/resources/templates/common/fragment/user/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/product/low.html
Labels: :memo: Status: Review Needed

#183 docs: Create sulbao-cicd.yml
  .github/workflows/sulbao-cicd.yml
Labels: :memo: Status: Review Needed

#185 feat: 유저페이지 카트 수량 표기
  src/main/java/com/finalproject/sulbao/cart/controller/CartController.java
  src/main/java/com/finalproject/sulbao/cart/controller/KakaoController.java
  src/main/java/com/finalproject/sulbao/cart/repository/CartRepository.java
  src/main/java/com/finalproject/sulbao/cart/service/CartService.java
  src/main/java/com/finalproject/sulbao/login/controller/UserAuthenticationSuccessHandler.java
  src/main/java/com/finalproject/sulbao/product/controller/UserProductController.java
  src/main/resources/templates/common/fragment/user/header.html
Labels: ✨ Type: Feature, :memo: Status: Review Needed

#186 fix: 상품등록,수정시 상품설명 등록안되는 오류
  src/main/resources/templates/admin/product/productDetail.html
  src/main/resources/templates/admin/product/productUpdate.html
Labels: :memo: Status: Review Needed

#188 fix: 판매자 주문조회 페이지 연결 에러 수정
  src/main/java/com/finalproject/sulbao/board/common/SessionHandler.java
  src/main/java/com/finalproject/sulbao/board/dto/UserDto.java
  src/main/java/com/finalproject/sulbao/cart/controller/OrderController.java
  src/main/java/com/finalproject/sulbao/cart/dto/SellerDto.java
Labels: :memo: Status: Review Needed, 🔨 Type: Fix

#191 feat: 환불, 배송 로직 추가 및 이메일 화면 수정
  src/main/java/com/finalproject/sulbao/cart/controller/KakaoController.java
  src/main/java/com/finalproject/sulbao/cart/controller/OrderController.java
  src/main/java/com/finalproject/sulbao/cart/dto/OrderListDTO.java
  src/main/java/com/finalproject/sulbao/cart/repository/CartRepository.java
  src/main/java/com/finalproject/sulbao/cart/repository/OrderRepository.java
  src/main/java/com/finalproject/sulbao/cart/service/CartService.java
  src/main/java/com/finalproject/sulbao/cart/service/OrderService.java
  src/main/java/com/finalproject/sulbao/login/model/service/EmailService.java
  src/main/java/com/finalproject/sulbao/product/repository/ProductRepository.java
  src/main/java/com/finalproject/sulbao/product/service/ProductService.java
  src/main/resources/templates/cart/memberorder.html
  src/main/resources/templates/cart/sellerorder.html
  src/main/resources/templates/present-email.html
Labels: ✨ Type: Feature, :memo: Status: Review Needed

#192 fix: 이메일, 주문조회 디자인 수정
  src/main/java/com/finalproject/sulbao/login/model/service/EmailService.java
  src/main/resources/templates/auth/verify-email.html
  src/main/resources/templates/cart/memberorder.html
  src/main/resources/templates/present-email.html
Labels: 🔨 Type: Fix

#193 fix: 상품카테고리 조회 및 메일발송 스케줄러 기능 추가
  src/main/java/com/finalproject/sulbao/board/controller/SearchController.java
  src/main/java/com/finalproject/sulbao/cart/repository/OrderRepository.java
  src/main/java/com/finalproject/sulbao/config/SchedulerConfiguration.java
  src/main/java/com/finalproject/sulbao/login/model/service/EmailService.java
  src/main/java/com/finalproject/sulbao/product/controller/UserProductController.java
  src/main/java/com/finalproject/sulbao/product/repository/ProductComparisonRepository.java
  src/main/java/com/finalproject/sulbao/product/repository/ProductRepository.java
  src/main/java/com/finalproject/sulbao/product/service/ProductService.java
  src/main/resources/templates/board/search-results.html
  src/main/resources/templates/index.html
  src/main/resources/templates/present-delay-email.html
  src/main/resources/templates/product/list.html
Labels: :memo: Status: Review Needed

#194 fix: 화면 디자인 수정
  src/main/resources/templates/cart/cart.html
  src/main/resources/templates/cart/order.html
  src/main/resources/templates/cart/ordercomplete.html
  src/main/resources/templates/cart/presentOrder.html
  src/main/resources/templates/cart/success.html
  src/main/resources/templates/presentcomplete.html
Labels: 🔨 Type: Fix

#195 fix: 뒤로가기시 토탈프라이스 0 원 에러 수정
  src/main/resources/templates/cart/cart.html
Labels: 🔨 Type: Fix

#196 feat: 디자인 및 메인페이지 조회기능 추가
  src/main/java/com/finalproject/sulbao/auth/controller/AuthController.java
  src/main/java/com/finalproject/sulbao/auth/model/dto/OrderStatus.java
  src/main/java/com/finalproject/sulbao/auth/service/AuthService.java
  src/main/java/com/finalproject/sulbao/cart/repository/OrderRepository.java
  src/main/java/com/finalproject/sulbao/product/controller/ProductController.java
  src/main/resources/templates/admin/index.html
  src/main/resources/templates/common/fragment/admin/header.html
Labels: :memo: Status: Review Needed

#200 게시판 관련 수정된 요구사항 반영
  build.gradle
  src/main/java/com/finalproject/sulbao/auth/controller/AuthController.java
  src/main/java/com/finalproject/sulbao/board/common/BadWordFilteringConfig.java
  src/main/java/com/finalproject/sulbao/board/common/TopTagScheduler.java
  src/main/java/com/finalproject/sulbao/board/controller/ZzanfeedController.java
  src/main/java/com/finalproject/sulbao/board/controller/ZzanpostController.java
  src/main/java/com/finalproject/sulbao/board/domain/Post.java
  src/main/java/com/finalproject/sulbao/board/domain/TopTag.java
  src/main/java/com/finalproject/sulbao/board/repository/PostRepository.java
  src/main/java/com/finalproject/sulbao/board/repository/TopTagRepository.java
  src/main/java/com/finalproject/sulbao/board/service/PostService.java
  src/main/resources/static/board/admin/list.css
  src/main/resources/static/board/image/thumbs-up-colored.png
  src/main/resources/static/board/image/thumbs-up.png
  src/main/resources/static/board/search.css
  src/main/resources/static/board/user/list.css
  src/main/resources/static/board/zzanfeed/detail.css
  src/main/resources/static/board/zzanfeed/edit.css
  src/main/resources/static/board/zzanfeed/list.css
  src/main/resources/static/board/zzanfeed/new.css
  src/main/resources/static/board/zzanpost/detail.css
  src/main/resources/static/board/zzanpost/edit.css
  src/main/resources/static/board/zzanpost/list.css
  src/main/resources/static/board/zzanpost/new.css
  src/main/resources/templates/board/admin/list.html
  src/main/resources/templates/board/search-results.html
  src/main/resources/templates/board/zzanfeed/detail.html
  src/main/resources/templates/board/zzanfeed/edit.html
  src/main/resources/templates/board/zzanfeed/list.html
  src/main/resources/templates/board/zzanfeed/new.html
  src/main/resources/templates/board/zzanpost/detail.html
  src/main/resources/templates/board/zzanpost/edit.html
  src/main/resources/templates/board/zzanpost/list.html
  src/main/resources/templates/board/zzanpost/new.html
  src/main/resources/templates/common/fragment/user/header.html
  src/test/java/com/finalproject/sulbao/BoardTest.java
Labels: :memo: Status: Review Needed

#201 !HOTFIX: 회원가입 오류 수정
  src/main/java/com/finalproject/sulbao/config/WebSecurityConfig.java
Labels: :memo: Status: Review Needed

#202 fix: 도메인 주소 직접입력 시큐리티
  src/main/java/com/finalproject/sulbao/cart/controller/CartController.java
  src/main/java/com/finalproject/sulbao/cart/controller/KakaoController.java
  src/main/java/com/finalproject/sulbao/cart/controller/OrderController.java
  src/main/resources/templates/error.html
Labels: :memo: Status: Review Needed, 🔨 Type: Fix

#203 fix: 시큐리티 인증 변경
  src/main/java/com/finalproject/sulbao/config/WebSecurityConfig.java
  src/main/java/com/finalproject/sulbao/magazine/controller/UserMagazineController.java
  src/main/resources/templates/magazine/list.html
Labels: :memo: Status: Review Needed, 🔨 Type: Fix

#204 feat : 회원탈퇴 기능 추가완료
  src/main/java/com/finalproject/sulbao/login/controller/LoginController.java
  src/main/java/com/finalproject/sulbao/login/controller/MemberProfileController.java
  src/main/java/com/finalproject/sulbao/login/model/entity/Login.java
  src/main/java/com/finalproject/sulbao/login/model/service/LoginService.java
  src/main/resources/templates/auth/signup.html
  src/main/resources/templates/auth/verifyagePage.html
  src/main/resources/templates/common/fragment/user/aside.html
  src/main/resources/templates/index.html
  src/main/resources/templates/mypage/myprofile.html
  src/main/resources/templates/mypage/pro-form.html
Labels: ✨ Type: Feature

#205 fix : 입점사 조회 버그 수정완료
  src/main/java/com/finalproject/sulbao/login/model/repository/LoginRepository.java
Labels: 🔨 Type: Fix

#206 fix: 상품 정보 길이로 인한 오류 수정
  src/main/java/com/finalproject/sulbao/product/controller/ProductController.java
  src/main/java/com/finalproject/sulbao/product/model/entity/Product.java
  src/main/resources/templates/admin/product/productDetail.html
  src/main/resources/templates/admin/product/productUpdate.html
Labels: :memo: Status: Review Needed

#208 Fix: 게시판 오류 수정
  src/main/java/com/finalproject/sulbao/board/common/SessionHandler.java
  src/main/java/com/finalproject/sulbao/board/controller/ManagementController.java
  src/main/java/com/finalproject/sulbao/board/controller/ZzanfeedController.java
  src/main/java/com/finalproject/sulbao/board/controller/ZzanpostController.java
  src/main/java/com/finalproject/sulbao/board/dto/UserDto.java
  src/main/java/com/finalproject/sulbao/board/repository/PostSpecification.java
  src/main/java/com/finalproject/sulbao/board/service/LikeService.java
  src/main/java/com/finalproject/sulbao/board/service/PostService.java
  src/main/resources/static/board/zzanfeed/list.css
  src/main/resources/static/board/zzanpost/list.css
  src/main/resources/templates/board/search-results.html
  src/main/resources/templates/board/zzanfeed/detail.html
  src/main/resources/templates/board/zzanpost/detail.html
  src/main/resources/templates/board/zzanpost/edit.html
  src/main/resources/templates/board/zzanpost/new.html
  src/test/java/com/finalproject/sulbao/BoardTest.java
Labels: :memo: Status: Review Needed

#209 HOTFIX : 입점사 조회 버그 수정완료, 비바톤배포키
  src/main/java/com/finalproject/sulbao/login/controller/LoginController.java
  src/main/java/com/finalproject/sulbao/login/model/repository/LoginRepository.java
  src/main/java/com/finalproject/sulbao/login/model/service/LoginService.java
  src/main/resources/templates/admin/member/sellerList.html
  src/main/resources/templates/auth/verifyagePage.html
Labels: 🔨 Type: Fix

#210 20240828: HOTFIX수정건
  src/main/java/com/finalproject/sulbao/board/common/SessionHandler.java
  src/main/java/com/finalproject/sulbao/board/controller/ManagementController.java
  src/main/java/com/finalproject/sulbao/board/controller/ZzanfeedController.java
  src/main/java/com/finalproject/sulbao/board/controller/ZzanpostController.java
  src/main/java/com/finalproject/sulbao/board/dto/UserDto.java
  src/main/java/com/finalproject/sulbao/board/repository/PostSpecification.java
  src/main/java/com/finalproject/sulbao/board/service/LikeService.java
  src/main/java/com/finalproject/sulbao/board/service/PostService.java
  src/main/java/com/finalproject/sulbao/login/controller/LoginController.java
  src/main/java/com/finalproject/sulbao/login/model/repository/LoginRepository.java
  src/main/java/com/finalproject/sulbao/login/model/service/LoginService.java
  src/main/resources/static/board/zzanfeed/list.css
  src/main/resources/static/board/zzanpost/list.css
  src/main/resources/templates/admin/member/sellerList.html
  src/main/resources/templates/auth/verifyagePage.html
  src/main/resources/templates/board/search-results.html
  src/main/resources/templates/board/zzanfeed/detail.html
  src/main/resources/templates/board/zzanpost/detail.html
  src/main/resources/templates/board/zzanpost/edit.html
  src/main/resources/templates/board/zzanpost/new.html
  src/test/java/com/finalproject/sulbao/BoardTest.java
Labels: :memo: Status: Review Needed

#211 fix: 웹 시큐리티 변경
  src/main/java/com/finalproject/sulbao/config/WebSecurityConfig.java
Labels: 🔨 Type: Fix

#213 fix: 웹 시큐리티 및 타이틀 변경
  src/main/java/com/finalproject/sulbao/config/WebSecurityConfig.java
  src/main/resources/templates/cart/cart.html
  src/main/resources/templates/cart/order.html
  src/main/resources/templates/cart/ordercomplete.html
  src/main/resources/templates/cart/presentOrder.html
  src/main/resources/templates/cart/success.html
  src/main/resources/templates/error.html
  src/main/resources/templates/magazine/detail.html
  src/main/resources/templates/magazine/list.html
  src/main/resources/templates/presentcomplete.html
  src/main/resources/templates/product/detail.html
  src/main/resources/templates/product/list.html
  src/main/resources/templates/product/low.html
Labels: :memo: Status: Review Needed, 🔨 Type: Fix

#214 fix: 웹 시큐리티 환불 변경
  src/main/java/com/finalproject/sulbao/config/WebSecurityConfig.java
Labels: :memo: Status: Review Needed, 🔨 Type: Fix

#215 fix: 웹 시큐리티 수정
  src/main/java/com/finalproject/sulbao/cart/controller/KakaoController.java
  src/main/java/com/finalproject/sulbao/config/WebSecurityConfig.java
  src/main/java/com/finalproject/sulbao/login/model/repository/LoginRepository.java
  src/main/java/com/finalproject/sulbao/login/model/service/LoginService.java
  src/main/resources/templates/error.html
Labels: 🔨 Type: Fix

#216 design: 에러 페이지 및 admin 헤더 변경
  src/main/resources/templates/common/fragment/admin/header.html
  src/main/resources/templates/error.html
Labels: :memo: Status: Review Needed

#220 Fix: 메인 페이지 배너 링크 수정
  src/main/resources/templates/board/zzanfeed/edit.html
  src/main/resources/templates/board/zzanfeed/new.html
  src/main/resources/templates/board/zzanpost/edit.html
  src/main/resources/templates/index.html
Labels: :memo: Status: Review Needed

#223 fix: mix오류
  src/main/resources/templates/auth/signup-seller.html
Labels: :memo: Status: Review Needed

#226 fix: 상품 등록/수정 정보등록안되는 부분 삭제
  src/main/java/com/finalproject/sulbao/product/model/entity/ProductComparison.java
  src/main/resources/templates/admin/product/productDetail.html
  src/main/resources/templates/admin/product/productUpdate.html
  src/main/resources/templates/product/detail.html
Labels: :memo: Status: Review Needed

#228 Fix: 짠피드 게시글 css 수정
  src/main/resources/static/board/zzanfeed/detail.css
Labels: 🔨 Type: Fix

#229 HOTFIX : HTTPS MixedContent 오류 해결
  src/main/resources/templates/common/layouts/userDefault.html
Labels: 🔨 Type: Fix

#231 HOTFIX : 회원탈퇴 오류 해결
  src/main/java/com/finalproject/sulbao/login/controller/MemberProfileController.java
Labels: 🔨 Type: Fix

#236 fix: 주문조회리스트 오류 수정
  src/main/java/com/finalproject/sulbao/cart/controller/OrderController.java
  src/main/java/com/finalproject/sulbao/cart/dto/OrderListDTO.java
  src/main/java/com/finalproject/sulbao/review/controller/ReviewController.java
  src/main/resources/templates/cart/memberorder.html
  src/main/resources/templates/cart/order.html
Labels: :memo: Status: Review Needed

#238 fix: 리뷰삭제 버튼 조건 추가
  src/main/resources/templates/review/list.html
Labels: :memo: Status: Review Needed
